import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Menu } from '@/components/ui/menu';
import { Typography } from '@/components/ui/typography';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const menuItems = [
  { label: 'About Me', href: '/about-me' },
  { label: 'Projects', href: '/projects' },
  { label: 'QA Blog', href: '/qa-blog' },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Menu menuItems={menuItems} />
        <Typography variant="h1">test</Typography>
        {children}
      </body>
    </html>
  );
}
